### ISSUE TITLE
Invalid tag name "sane@2.2.0": Tags may not have any characters that encodeURIComponent encodes.

### ISSUE THREAD

**Issue by a-x-** [npm/npm-package-arg#36]
I don't use sane directly and I has not updated any packages targetly,
but today `npm i` becomes broken

npm 6.8.0
node v11.10.1

package-json: 
- **dependencies.sane**
```json5
    {
      "version": "2.2.0",
      "resolved": "https://registry.npmjs.org/svgo-loader/-/svgo-loader-2.2.0.tgz",
      "integrity": "sha512-AtIy4kmUQc1zo+QK3ZFvRrULRZAhUC63cLJxdVo1cONZ9WeYAkySUlaB05uZKKcYpsTb/9tDsBSXMab3/0QWtw==",
      "dev": true,
      "requires": {
        "js-yaml": "^3.12.0",
        "loader-utils": "^1.0.3"
      },
      // ...
    }
```
- **dependencies["jest-haste-map"].requires.sane**:  "^2.0.0"

https://github.com/amasad/sane/issues/138

```
Unhandled rejection Error: Invalid tag name "sane@2.2.0": Tags may not have any characters that encodeURIComponent encodes.
    at invalidTagName (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:87:15)
    at fromRegistry (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:291:13)
    at Function.resolve (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:77:12)
    at doesChildVersionMatch (/usr/local/lib/node_modules/npm/lib/install/deps.js:75:25)
    at isDep (/usr/local/lib/node_modules/npm/lib/install/deps.js:147:27)
    at addRequiredDep (/usr/local/lib/node_modules/npm/lib/install/deps.js:159:13)
```

**Comment by isaacs** [comment]
I believe that this was fixed quite some time ago.  Please let us know if it's still an issue.
