### ISSUE TITLE
Webpack fails after updating to version 8

### ISSUE THREAD

**Issue by joelspadin-garmin** [npm/npm-package-arg#47]
# What / Why

Using npm-package-arg version 8 in a project that uses Webpack results in a compilation error:

```
 WARNING in ./node_modules/npm-package-arg/node_modules/semver/index.js 3:51-64
    Critical dependency: the request of a dependency is an expression
     @ ./node_modules/npm-package-arg/npa.js
```

It looks like semver version 7 was restructured in a way that confuses Webpack's tree shaking. The packed script fails at runtime because Webpack's tree shaking discarded some necessary parts of semver:

```
Error: Cannot find module './functions/valid'
	at webpackEmptyContext (d:\projects\vscode\private-extension-manager\extension\dist\extension.js:2775:10)
	at lazyRequire (d:\projects\vscode\private-extension-manager\extension\dist\extension.js:2706:75)
	at Object.get [as valid] (d:\projects\vscode\private-extension-manager\extension\dist\extension.js:2713:19)
	at fromRegistry (d:\projects\vscode\private-extension-manager\extension\dist\extension.js:3336:26)
	at resolve (d:\projects\vscode\private-extension-manager\extension\dist\extension.js:3129:12)
	at npa (d:\projects\vscode\private-extension-manager\extension\dist\extension.js:3100:10)
	at Registry.<anonymous> (d:\projects\vscode\private-extension-manager\extension\dist\extension.js:12819:26)
    ...
```

### Steps to Reproduce

1. Create a script containing
```js
const npa = require('npm-package-arg');
```
2. Webpack it.

To reproduce in an existing project:

1. Check out https://github.com/joelspadin-garmin/vscode-private-extension-manager
2. Open the "extension" folder. 
3. `npm i npm-package-arg@latest`
4. `npm run compile`

### Expected Behavior

Webpack should compile successfully, and the packed script should work.

## References

* Related to https://github.com/npm/node-semver/issues/306
* Related to https://github.com/npm/node-semver/issues/299

**Comment by isaacs** [comment]
fixed in node-semver
